dist: xenial
language: rust
rust:
- nightly
- beta
- 1.28.0 # stable
addons:
  apt:
    packages:
    - libgtk-3-dev
    - libmount-dev
env:
  - GTK=3.14
  - GTK=3.18
  - GTK=3.22.30
  - GTK=3.24
script:
  - ./build_travis.sh
